### ISSUE TITLE
How to use the TypeScript library?

### ISSUE THREAD

**Issue by felipecrs** [gerritkit/client#23]
I'm trying something like:

```ts
import { GerritNative } from "@gerritkit/native";

(async () => {
    const gerrit = new GerritNative("https://review.gerrithub.io", {
        username: "felipecrs",
        password: "<hidden>"
    })

    const changes = await gerrit.changeEndpoints.queryChanges({
        params: {
            q: "owner:felipecrs"
        }
    })

    changes.forEach(change => console.log(change))
})();
```

But VS Code does not understand the types properly:

![image](https://user-images.githubusercontent.com/29582865/113738032-f013e180-96d4-11eb-9876-801281213510.png)

If I do something like:

```ts
import { GerritNative } from "@gerritkit/native/target/ts";
```

Then the types are properly recognized:

![image](https://user-images.githubusercontent.com/29582865/113738238-1e91bc80-96d5-11eb-9c07-e9ed23743391.png)

But then code doesn't run:

```sh-session
❯ npx ts-node index.ts
/home/felipecrs/repos/gerritkit-test/node_modules/@gerritkit/native/target/ts/index.ts:1
import { UnionToIntersection } from '@qiwi/substrate'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/home/felipecrs/repos/gerritkit-test/node_modules/ts-node/src/index.ts:1045:43)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/felipecrs/repos/gerritkit-test/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Comment by pismenskiy** [comment]
Hi! which version of node and npm are you using?
Your code works correctly when I use it

![image](https://user-images.githubusercontent.com/12610792/113740554-79450b80-9709-11eb-9a2b-cb0dda0015a6.png)

I am using v14.15.4 node and 6.14.10 npm

**Comment by felipecrs** [comment]
```sh-session
❯ node --version
v14.16.0
❯ npm --version
7.8.0
```

The first snippet I sent indeed works, but, as I said, the problem is that the types are not properly recognized in my IDE. Did you mean the second snippet works for you?

```ts
import { GerritNative } from "@gerritkit/native/target/ts";

(async () => {
    const gerrit = new GerritNative("https://review.gerrithub.io", {
        username: "felipecrs",
        password: "<hidden>"
    })

    const changes = await gerrit.changeEndpoints.queryChanges({
        params: {
            q: "owner:felipecrs"
        }
    })

    changes.forEach(change => console.log(change))
})();
```

**Comment by pismenskiy** [comment]
HI @felipecrs, check the last update, probably we have fixed the problem

**Comment by felipecrs** [comment]
Wow, awesome! It's now working fine:

![image](https://user-images.githubusercontent.com/29582865/113882128-6bd46380-9793-11eb-8c4f-469a6d724b72.png)

Thank you so much!
